######################################################################
##
## Filename: load_bram.udo
## Created on: Wed Mar 26 1:22:15 PM Eastern Daylight Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
