######################################################################
##
## Filename: tb.udo
## Created on: Sun Mar 23 12:59:49 PM Eastern Daylight Time 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
