onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb/SW_I
add wave -noupdate /tb/RESET_I
add wave -noupdate /tb/CamClk
add wave -noupdate /tb/CamClk_180
add wave -noupdate /tb/S_AXI_ACLK
add wave -noupdate /tb/S_AXI_ARESETN
add wave -noupdate /tb/S_AXI_AWADDR
add wave -noupdate /tb/S_AXI_AWVALID
add wave -noupdate /tb/S_AXI_WDATA
add wave -noupdate /tb/S_AXI_WSTRB
add wave -noupdate /tb/S_AXI_WVALID
add wave -noupdate /tb/S_AXI_BREADY
add wave -noupdate /tb/S_AXI_ARADDR
add wave -noupdate /tb/S_AXI_ARVALID
add wave -noupdate /tb/S_AXI_RREADY
add wave -noupdate /tb/m_axi_aclk
add wave -noupdate /tb/m_axi_aresetn
add wave -noupdate /tb/m_axi_arready
add wave -noupdate /tb/m_axi_rvalid
add wave -noupdate /tb/m_axi_rdata
add wave -noupdate /tb/m_axi_rresp
add wave -noupdate /tb/m_axi_rlast
add wave -noupdate /tb/m_axi_awready
add wave -noupdate /tb/m_axi_wready
add wave -noupdate /tb/m_axi_bvalid
add wave -noupdate /tb/m_axi_bresp
add wave -noupdate /tb/LED_O
add wave -noupdate /tb/CAMA_MCLK_O
add wave -noupdate /tb/CAMA_RST_O
add wave -noupdate /tb/CAMA_PWDN_O
add wave -noupdate /tb/CAMX_VDDEN_O
add wave -noupdate /tb/CAMB_MCLK_O
add wave -noupdate /tb/CAMB_RST_O
add wave -noupdate /tb/CAMB_PWDN_O
add wave -noupdate /tb/CAMA_CLK
add wave -noupdate /tb/S_AXI_ARREADY
add wave -noupdate /tb/S_AXI_RDATA
add wave -noupdate /tb/S_AXI_RRESP
add wave -noupdate /tb/S_AXI_RVALID
add wave -noupdate /tb/S_AXI_WREADY
add wave -noupdate /tb/S_AXI_BRESP
add wave -noupdate /tb/S_AXI_BVALID
add wave -noupdate /tb/S_AXI_AWREADY
add wave -noupdate /tb/md_error
add wave -noupdate /tb/m_axi_arvalid
add wave -noupdate /tb/m_axi_araddr
add wave -noupdate /tb/m_axi_arlen
add wave -noupdate /tb/m_axi_arsize
add wave -noupdate /tb/m_axi_arburst
add wave -noupdate /tb/m_axi_arprot
add wave -noupdate /tb/m_axi_arcache
add wave -noupdate /tb/m_axi_rready
add wave -noupdate /tb/m_axi_awvalid
add wave -noupdate /tb/m_axi_awaddr
add wave -noupdate /tb/m_axi_awlen
add wave -noupdate /tb/m_axi_awsize
add wave -noupdate /tb/m_axi_awburst
add wave -noupdate /tb/m_axi_awprot
add wave -noupdate /tb/m_axi_awcache
add wave -noupdate /tb/m_axi_wvalid
add wave -noupdate /tb/m_axi_wdata
add wave -noupdate /tb/m_axi_wstrb
add wave -noupdate /tb/m_axi_wlast
add wave -noupdate /tb/m_axi_bready
add wave -noupdate /tb/CAMA_SDA
add wave -noupdate /tb/CAMA_SCL
add wave -noupdate /tb/CAMA_D_I
add wave -noupdate /tb/CAMA_PCLK_I
add wave -noupdate /tb/CAMA_LV_I
add wave -noupdate /tb/CAMA_FV_I
add wave -noupdate /tb/CAMB_SDA
add wave -noupdate /tb/CAMB_SCL
add wave -noupdate /tb/CAMB_D_I
add wave -noupdate /tb/CAMB_PCLK_I
add wave -noupdate /tb/CAMB_LV_I
add wave -noupdate /tb/CAMB_FV_I
add wave -noupdate /tb/curr_state
add wave -noupdate /glbl/GSR
add wave -noupdate /tb/state1
add wave -noupdate /tb/state2
add wave -noupdate /tb/state3
add wave -noupdate /tb/state4
add wave -noupdate /tb/m_axi_aclk
add wave -noupdate /tb/m_axi_aresetn
add wave -noupdate /tb/m_axi_arready
add wave -noupdate /tb/m_axi_rvalid
add wave -noupdate /tb/m_axi_rdata
add wave -noupdate /tb/m_axi_rresp
add wave -noupdate /tb/m_axi_rlast
add wave -noupdate /tb/m_axi_awready
add wave -noupdate /tb/m_axi_wready
add wave -noupdate /tb/m_axi_bvalid
add wave -noupdate /tb/m_axi_bresp
add wave -noupdate /tb/m_axi_arvalid
add wave -noupdate /tb/m_axi_araddr
add wave -noupdate /tb/m_axi_arlen
add wave -noupdate /tb/m_axi_arsize
add wave -noupdate /tb/m_axi_arburst
add wave -noupdate /tb/m_axi_arprot
add wave -noupdate /tb/m_axi_arcache
add wave -noupdate /tb/m_axi_rready
add wave -noupdate /tb/m_axi_awvalid
add wave -noupdate /tb/m_axi_awaddr
add wave -noupdate /tb/m_axi_awlen
add wave -noupdate /tb/m_axi_awsize
add wave -noupdate /tb/m_axi_awburst
add wave -noupdate /tb/m_axi_awprot
add wave -noupdate /tb/m_axi_awcache
add wave -noupdate /tb/m_axi_wvalid
add wave -noupdate /tb/m_axi_wdata
add wave -noupdate /tb/m_axi_wstrb
add wave -noupdate /tb/m_axi_wlast
add wave -noupdate /tb/m_axi_bready
add wave -noupdate /tb/curr_state
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_fifo_valid_write_xfer
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_fifo_valid_read_xfer
add wave -noupdate /tb/uut/USER_LOGIC_I/Bus2IP_Reset
add wave -noupdate /tb/uut/USER_LOGIC_I/axi_to_pxconv_valid
add wave -noupdate /tb/uut/USER_LOGIC_I/fifo_data_out
add wave -noupdate /tb/uut/USER_LOGIC_I/fifo_empty
add wave -noupdate /tb/uut/USER_LOGIC_I/read_fifo_state
add wave -noupdate /tb/uut/USER_LOGIC_I/cama_sm_state
add wave -noupdate /tb/uut/USER_LOGIC_I/axi_to_pxconv_data
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_to_axi_ready_to_rd
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_to_bram_we
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_to_bram_data
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_to_bram_wr_en
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_to_bram_addr
add wave -noupdate /tb/uut/USER_LOGIC_I/bram_busy
add wave -noupdate -radix hexadecimal /tb/uut/USER_LOGIC_I/pa_wr_addr
add wave -noupdate /tb/uut/USER_LOGIC_I/wnd_in_bram
add wave -noupdate /tb/uut/USER_LOGIC_I/Bus2IP_Clk
add wave -noupdate /tb/uut/USER_LOGIC_I/Bus2IP_Resetn
add wave -noupdate /tb/uut/USER_LOGIC_I/Bus2IP_Data
add wave -noupdate /tb/uut/USER_LOGIC_I/IP2Bus_Data
add wave -noupdate /tb/uut/USER_LOGIC_I/IP2Bus_RdAck
add wave -noupdate /tb/uut/USER_LOGIC_I/IP2Bus_WrAck
add wave -noupdate /tb/uut/USER_LOGIC_I/ip2bus_mstrd_req
add wave -noupdate /tb/uut/USER_LOGIC_I/ip2bus_mstwr_req
add wave -noupdate /tb/uut/USER_LOGIC_I/ip2bus_mst_addr
add wave -noupdate /tb/uut/USER_LOGIC_I/ip2bus_mst_be
add wave -noupdate /tb/uut/USER_LOGIC_I/ip2bus_mst_length
add wave -noupdate /tb/uut/USER_LOGIC_I/ip2bus_mst_type
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_ip2bus_data
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_write_ack
add wave -noupdate /tb/uut/USER_LOGIC_I/bus2ip_mst_cmdack
add wave -noupdate /tb/uut/USER_LOGIC_I/bus2ip_mst_cmplt
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_read_ack
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_reg
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_byte_we
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_cntl_rd_req
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_cntl_wr_req
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_cntl_burst
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_ip2bus_addr
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_xfer_length
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_xfer_reg_len
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_ip2bus_be
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_go
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_cmd_sm_state
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_inst/clk
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_inst/rst
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_inst/axi_to_pxconv_data
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_inst/axi_to_pxconv_valid
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_inst/pixel_ack
add wave -noupdate -radix hexadecimal /tb/uut/USER_LOGIC_I/pxconv_inst/pxconv_to_axi_ready_to_rd
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_inst/pxconv_to_axi_mst_length
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_inst/pxconv_to_bram_we
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_inst/pxconv_to_bram_data
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_inst/pxconv_to_bram_wr_en
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_inst/pxconv_to_bram_addr
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_inst/busy
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_inst/wnd_in_bram
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_inst/px_low_red
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_inst/px_low_blue
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_inst/px_low_green
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_inst/px_low_grey
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_inst/px_cnt
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_inst/row_cnt
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_inst/px_cnt_d
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_inst/axi_to_pxconv_data_d
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_inst/axi_to_pxconv_valid_d
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {396548 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 394
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {769 ps}
