onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb/SW_I
add wave -noupdate /tb/RESET_I
add wave -noupdate /tb/S_AXI_ACLK
add wave -noupdate /tb/S_AXI_ARESETN
add wave -noupdate /tb/S_AXI_AWADDR
add wave -noupdate /tb/S_AXI_AWVALID
add wave -noupdate /tb/S_AXI_WDATA
add wave -noupdate /tb/S_AXI_WSTRB
add wave -noupdate /tb/S_AXI_WVALID
add wave -noupdate /tb/S_AXI_BREADY
add wave -noupdate /tb/S_AXI_ARADDR
add wave -noupdate /tb/S_AXI_ARVALID
add wave -noupdate /tb/S_AXI_RREADY
add wave -noupdate /tb/m_axi_aclk
add wave -noupdate /tb/m_axi_aresetn
add wave -noupdate /tb/m_axi_arready
add wave -noupdate /tb/m_axi_rvalid
add wave -noupdate /tb/m_axi_rdata
add wave -noupdate /tb/m_axi_rresp
add wave -noupdate /tb/m_axi_rlast
add wave -noupdate /tb/m_axi_awready
add wave -noupdate /tb/m_axi_wready
add wave -noupdate /tb/m_axi_bvalid
add wave -noupdate /tb/m_axi_bresp
add wave -noupdate /tb/S_AXI_ARREADY
add wave -noupdate /tb/S_AXI_RDATA
add wave -noupdate /tb/S_AXI_RRESP
add wave -noupdate /tb/S_AXI_RVALID
add wave -noupdate /tb/S_AXI_WREADY
add wave -noupdate /tb/S_AXI_BRESP
add wave -noupdate /tb/S_AXI_BVALID
add wave -noupdate /tb/S_AXI_AWREADY
add wave -noupdate /tb/md_error
add wave -noupdate /tb/m_axi_arvalid
add wave -noupdate /tb/m_axi_araddr
add wave -noupdate /tb/m_axi_arlen
add wave -noupdate /tb/m_axi_arsize
add wave -noupdate /tb/m_axi_arburst
add wave -noupdate /tb/m_axi_arprot
add wave -noupdate /tb/m_axi_arcache
add wave -noupdate /tb/m_axi_rready
add wave -noupdate /tb/m_axi_awvalid
add wave -noupdate /tb/m_axi_awaddr
add wave -noupdate /tb/m_axi_awlen
add wave -noupdate /tb/m_axi_awsize
add wave -noupdate /tb/m_axi_awburst
add wave -noupdate /tb/m_axi_awprot
add wave -noupdate /tb/m_axi_awcache
add wave -noupdate /tb/m_axi_wvalid
add wave -noupdate /tb/m_axi_wdata
add wave -noupdate /tb/m_axi_wstrb
add wave -noupdate /tb/m_axi_wlast
add wave -noupdate /tb/m_axi_bready
add wave -noupdate /tb/curr_state
add wave -noupdate /tb/counter
add wave -noupdate /glbl/GSR
add wave -noupdate /tb/uut/USER_LOGIC_I/C_MST_NATIVE_DATA_WIDTH
add wave -noupdate /tb/uut/USER_LOGIC_I/C_LENGTH_WIDTH
add wave -noupdate /tb/uut/USER_LOGIC_I/C_MST_AWIDTH
add wave -noupdate /tb/uut/USER_LOGIC_I/C_NUM_REG
add wave -noupdate /tb/uut/USER_LOGIC_I/C_SLV_DWIDTH
add wave -noupdate /tb/uut/USER_LOGIC_I/START_ADDR_REF
add wave -noupdate /tb/uut/USER_LOGIC_I/END_ADDR_REF
add wave -noupdate /tb/uut/USER_LOGIC_I/START_ADDR_SEARCH
add wave -noupdate /tb/uut/USER_LOGIC_I/END_ADDR_SEARCH
add wave -noupdate /tb/uut/USER_LOGIC_I/BRAM_ADDR_WIDTH
add wave -noupdate /tb/uut/USER_LOGIC_I/Bus2IP_Clk
add wave -noupdate /tb/uut/USER_LOGIC_I/Bus2IP_Resetn
add wave -noupdate /tb/uut/USER_LOGIC_I/Bus2IP_Data
add wave -noupdate /tb/uut/USER_LOGIC_I/Bus2IP_BE
add wave -noupdate /tb/uut/USER_LOGIC_I/Bus2IP_RdCE
add wave -noupdate /tb/uut/USER_LOGIC_I/Bus2IP_WrCE
add wave -noupdate /tb/uut/USER_LOGIC_I/IP2Bus_Data
add wave -noupdate /tb/uut/USER_LOGIC_I/IP2Bus_RdAck
add wave -noupdate /tb/uut/USER_LOGIC_I/IP2Bus_WrAck
add wave -noupdate /tb/uut/USER_LOGIC_I/IP2Bus_Error
add wave -noupdate /tb/uut/USER_LOGIC_I/ip2bus_mstrd_req
add wave -noupdate /tb/uut/USER_LOGIC_I/ip2bus_mstwr_req
add wave -noupdate /tb/uut/USER_LOGIC_I/ip2bus_mst_addr
add wave -noupdate /tb/uut/USER_LOGIC_I/ip2bus_mst_be
add wave -noupdate /tb/uut/USER_LOGIC_I/ip2bus_mst_length
add wave -noupdate /tb/uut/USER_LOGIC_I/ip2bus_mst_type
add wave -noupdate /tb/uut/USER_LOGIC_I/ip2bus_mst_lock
add wave -noupdate /tb/uut/USER_LOGIC_I/ip2bus_mst_reset
add wave -noupdate /tb/uut/USER_LOGIC_I/bus2ip_mst_cmdack
add wave -noupdate /tb/uut/USER_LOGIC_I/bus2ip_mst_cmplt
add wave -noupdate /tb/uut/USER_LOGIC_I/bus2ip_mst_error
add wave -noupdate /tb/uut/USER_LOGIC_I/bus2ip_mst_rearbitrate
add wave -noupdate /tb/uut/USER_LOGIC_I/bus2ip_mst_cmd_timeout
add wave -noupdate /tb/uut/USER_LOGIC_I/bus2ip_mstrd_d
add wave -noupdate /tb/uut/USER_LOGIC_I/bus2ip_mstrd_rem
add wave -noupdate /tb/uut/USER_LOGIC_I/bus2ip_mstrd_sof_n
add wave -noupdate /tb/uut/USER_LOGIC_I/bus2ip_mstrd_eof_n
add wave -noupdate /tb/uut/USER_LOGIC_I/bus2ip_mstrd_src_rdy_n
add wave -noupdate /tb/uut/USER_LOGIC_I/bus2ip_mstrd_src_dsc_n
add wave -noupdate /tb/uut/USER_LOGIC_I/ip2bus_mstrd_dst_rdy_n
add wave -noupdate /tb/uut/USER_LOGIC_I/ip2bus_mstrd_dst_dsc_n
add wave -noupdate /tb/uut/USER_LOGIC_I/ip2bus_mstwr_d
add wave -noupdate /tb/uut/USER_LOGIC_I/ip2bus_mstwr_rem
add wave -noupdate /tb/uut/USER_LOGIC_I/ip2bus_mstwr_src_rdy_n
add wave -noupdate /tb/uut/USER_LOGIC_I/ip2bus_mstwr_src_dsc_n
add wave -noupdate /tb/uut/USER_LOGIC_I/ip2bus_mstwr_sof_n
add wave -noupdate /tb/uut/USER_LOGIC_I/ip2bus_mstwr_eof_n
add wave -noupdate /tb/uut/USER_LOGIC_I/bus2ip_mstwr_dst_rdy_n
add wave -noupdate /tb/uut/USER_LOGIC_I/bus2ip_mstwr_dst_dsc_n
add wave -noupdate /tb/uut/USER_LOGIC_I/slv_reg0
add wave -noupdate /tb/uut/USER_LOGIC_I/slv_reg1
add wave -noupdate /tb/uut/USER_LOGIC_I/slv_reg2
add wave -noupdate /tb/uut/USER_LOGIC_I/slv_reg3
add wave -noupdate /tb/uut/USER_LOGIC_I/slv_reg4
add wave -noupdate /tb/uut/USER_LOGIC_I/slv_reg_write_sel
add wave -noupdate /tb/uut/USER_LOGIC_I/slv_reg_read_sel
add wave -noupdate /tb/uut/USER_LOGIC_I/slv_ip2bus_data
add wave -noupdate /tb/uut/USER_LOGIC_I/slv_read_ack
add wave -noupdate /tb/uut/USER_LOGIC_I/slv_write_ack
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_ip2bus_data
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_reg_write_req
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_reg_read_req
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_reg_write_sel
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_reg_read_sel
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_write_ack
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_read_ack
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_reg
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_byte_we
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_cntl_rd_req
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_cntl_wr_req
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_cntl_bus_lock
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_cntl_burst
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_ip2bus_addr
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_xfer_length
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_xfer_reg_len
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_ip2bus_be
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_go
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_cmd_sm_state
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_cmd_sm_set_done
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_cmd_sm_set_error
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_cmd_sm_set_timeout
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_cmd_sm_busy
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_cmd_sm_clr_go
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_cmd_sm_rd_req
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_cmd_sm_wr_req
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_cmd_sm_reset
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_cmd_sm_bus_lock
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_cmd_sm_ip2bus_addr
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_cmd_sm_ip2bus_be
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_cmd_sm_xfer_type
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_cmd_sm_xfer_length
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_cmd_sm_start_rd_llink
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_cmd_sm_start_wr_llink
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_llrd_sm_state
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_llrd_sm_dst_rdy
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_llwr_sm_state
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_llwr_sm_src_rdy
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_llwr_sm_sof
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_llwr_sm_eof
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_llwr_byte_cnt
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_fifo_valid_write_xfer
add wave -noupdate /tb/uut/USER_LOGIC_I/mst_fifo_valid_read_xfer
add wave -noupdate /tb/uut/USER_LOGIC_I/Bus2IP_Reset
add wave -noupdate /tb/uut/USER_LOGIC_I/axi_to_pxconv_valid
add wave -noupdate /tb/uut/USER_LOGIC_I/fifo_data_out
add wave -noupdate /tb/uut/USER_LOGIC_I/fifo_empty
add wave -noupdate /tb/uut/USER_LOGIC_I/read_fifo_state
add wave -noupdate /tb/uut/USER_LOGIC_I/cama_sm_state
add wave -noupdate /tb/uut/USER_LOGIC_I/axi_to_pxconv_data
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_to_axi_ready_to_rd
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_to_bram_we
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_to_bram_data
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_to_bram_wr_en
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_to_bram_addr
add wave -noupdate /tb/uut/USER_LOGIC_I/bram_busy
add wave -noupdate /tb/uut/USER_LOGIC_I/pa_wr_addr
add wave -noupdate /tb/uut/USER_LOGIC_I/wnd_in_bram
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_mst_length
add wave -noupdate /tb/uut/USER_LOGIC_I/axi_to_pxconv_valid_search
add wave -noupdate /tb/uut/USER_LOGIC_I/fifo_data_out_search
add wave -noupdate /tb/uut/USER_LOGIC_I/fifo_empty_search
add wave -noupdate /tb/uut/USER_LOGIC_I/read_fifo_state_search
add wave -noupdate /tb/uut/USER_LOGIC_I/axi_to_pxconv_data_search
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_to_axi_ready_to_rd_search
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_to_bram_we_search
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_to_bram_data_search
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_to_bram_wr_en_search
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_to_bram_addr_search
add wave -noupdate /tb/uut/USER_LOGIC_I/bram_busy_search
add wave -noupdate /tb/uut/USER_LOGIC_I/pb_wr_addr
add wave -noupdate /tb/uut/USER_LOGIC_I/wnd_in_bram_search
add wave -noupdate /tb/uut/USER_LOGIC_I/pxconv_mst_length_search
add wave -noupdate /tb/uut/USER_LOGIC_I/fifo_ref_sel
add wave -noupdate /tb/uut/USER_LOGIC_I/fifo_search_sel
add wave -noupdate /tb/uut/USER_LOGIC_I/fifo_search_wr_en
add wave -noupdate /tb/uut/USER_LOGIC_I/fifo_ref_wr_en
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {62500 ps} {63500 ps}
